// <auto-generated />
using System;
using GameStoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStoreAPI.Migrations
{
    [DbContext(typeof(GameStoreDbContext))]
    partial class GameStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2");

            modelBuilder.Entity("GameStoreAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Downloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("Reviews")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "Top Seller",
                            Category = "action",
                            Description = "A futuristic action-packed RPG with cyber-enhanced warriors.",
                            Downloads = 200000,
                            Genre = "Action RPG",
                            Image = "https://pub-f354ec240bea480db7320bd0e29d972e.r2.dev/sites/2/2025/03/Atomfall-hero-d25f8e2fb0c6e97799e1.jpg",
                            IsFavorite = false,
                            Platforms = "PC,PS5,Xbox",
                            Price = 59.99m,
                            Rating = 4.8m,
                            Reviews = 1500,
                            Title = "Atomfall"
                        },
                        new
                        {
                            Id = 2,
                            Badge = "Best Racing Game",
                            Category = "racing",
                            Description = "High-speed adrenaline-fueled racing with realistic physics.",
                            Downloads = 500000,
                            Genre = "Racing",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrGksnJpXiB0xcE4ROvTcnFjS7rZziRL4wWw&s",
                            IsFavorite = false,
                            Platforms = "PC,PS5,Xbox",
                            Price = 49.99m,
                            Rating = 4.5m,
                            Reviews = 980,
                            Title = "Racing Rivals"
                        },
                        new
                        {
                            Id = 3,
                            Badge = "Editor's Choice",
                            Category = "adventure",
                            Description = "An open-world fantasy adventure filled with mythical creatures.",
                            Downloads = 300000,
                            Genre = "Adventure RPG",
                            Image = "https://thefinalfantasy.net/gallery/wallpaper/ff-mystic-quest/ff-mystic-quest-wallpaper-2.jpg",
                            IsFavorite = false,
                            Platforms = "PC,Switch",
                            Price = 39.99m,
                            Rating = 4.7m,
                            Reviews = 2000,
                            Title = "Mystic Quest"
                        },
                        new
                        {
                            Id = 4,
                            Badge = "Top Multiplayer",
                            Category = "shooter",
                            Description = "Mini Royale elevates the beloved toy soldier experience with creative weapons, gadgets, and dynamic movement. Swing from curtain rods, dodge between towering action figures, and zip across the room using the game's signature grapple gun. Every match offers fresh and exciting ways to outmaneuver your opponents.",
                            Downloads = 1000000,
                            Genre = "Shooter",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXVIFt6G3VaWO1iR0G4bjdn-bna6nFddmRrg&s",
                            IsFavorite = false,
                            Platforms = "PC,PS5,Xbox",
                            Price = 69.99m,
                            Rating = 4.6m,
                            Reviews = 3000,
                            Title = "Mini Royale: The Ultimate Toy Soldier Shooter!"
                        },
                        new
                        {
                            Id = 5,
                            Badge = "Best Strategy Game",
                            Category = "adventure",
                            Description = "Experience an epic action-adventure story set in feudal Japan! Become a lethal shinobi assassin and powerful legendary samurai as you explore a beautiful open world in a time of chaos.",
                            Downloads = 150000,
                            Genre = "Strategy",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4M0BgASIn8R5h1LlbKEjSbLP4Yj2VBnnmQw&s",
                            IsFavorite = false,
                            Platforms = "PC",
                            Price = 29.99m,
                            Rating = 4.4m,
                            Reviews = 800,
                            Title = "Assassin's Creed Shadows"
                        });
                });

            modelBuilder.Entity("GameStoreAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 12, 15, 3, 55, 818, DateTimeKind.Utc).AddTicks(298),
                            Email = "admin@gamestore.com",
                            PasswordHash = "$2a$11$KzQ3Qe4EHUEutQxiZgexs.2zu0yKQoIIpi.xq7eD1jN.89nMdUouG",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
